"use client";

import {
  ArrowRightIcon,
  BankIcon,
  ChartBarIcon,
  ChartDonutIcon,
  ChartLineUpIcon,
  ChatCircleTextIcon,
  CheckIcon,
  CreditCardIcon,
  GearSixIcon,
  GlobeHemisphereWestIcon,
  HouseIcon,
  MoonStarsIcon,
  PaperPlaneTiltIcon,
  PlusIcon,
  SignOutIcon,
  SparkleIcon,
  SunDimIcon,
  TagIcon,
  TargetIcon,
  WalletIcon
} from "@phosphor-icons/react/dist/ssr";

export const AppIcons = {
  arrowRight: ArrowRightIcon,
  bank: BankIcon,
  chartDonut: ChartDonutIcon,
  chartLineUp: ChartLineUpIcon,
  chat: ChatCircleTextIcon,
  check: CheckIcon,
  creditCard: CreditCardIcon,
  gear: GearSixIcon,
  globe: GlobeHemisphereWestIcon,
  house: HouseIcon,
  moon: MoonStarsIcon,
  paperPlane: PaperPlaneTiltIcon,
  plus: PlusIcon,
  signOut: SignOutIcon,
  sparkle: SparkleIcon,
  sun: SunDimIcon,
  target: TargetIcon,
  wallet: WalletIcon,
  transactions: WalletIcon,
  dashboard: ChartLineUpIcon,
  reports: ChartDonutIcon,
  goals: TargetIcon,
  settings: GearSixIcon,
  accounts: BankIcon,
  categories: TagIcon,
  budget: ChartBarIcon
};